### ISSUE TITLE
Creation of a URI class

### ISSUE THREAD

**Issue by usr99** [tmatis/webserv#18]
An URI is composed of different segments : scheme, authority, path, query and fragment.
![Capture](https://user-images.githubusercontent.com/61255495/136983213-f5af543e-59e2-4b6f-9ef2-ea504101d540.PNG)
(see [https://datatracker.ietf.org/doc/html/rfc3986#section-3](url) for more information)

### Why do we need a class for this ?

In accordance to the rfc2616, we must comply to this rule :
> - Servers MUST accept absolute URIs.

To find the specified ressource in URI, only the `path` segment is useful and for cgi requests with GET we need the `query` segment.
`scheme` must be http, `authority` is useless because we only have a unique server_name for each address:port and I still don't know  what to do with `fragment`.

### What should we code for that ?
HTTPRequest should include a class for URIs instead of a simple std::string to make request handling easier later.
The new parsing functions must be able to distinguish absolute URIs from relative URIs formatted as `<path>[?query][#fragment]` and fill an URI object with these values.

**Comment by tmatis** [comment]
https://en.wikipedia.org/wiki/Query_string
