### ISSUE TITLE
setup a client class

### ISSUE THREAD

**Issue by nouchata** [tmatis/webserv#6]
the client class has to contain the state of the client (idle, answer waiting, request pending, disconnected ...) and all informations about him (fds, infos ...).

though there are no clues about the scope of the class (stands for a client or a whole set of clients for a internal server), i would say that a set of clients type class would be neater to manage them after a disconnection or simply to keep an easier track of clients related to a server but this can also be done in a server class so idk asw 🙏🏽

flemme de make an interface for this so picture it yourself

**Comment by usr99** [comment]
Since my branch has been merged to master by nouchata's pull request, this issue is no longer relevant.
